storage:
  endPoint: 'localhost'
  port: 9500
  useSSL: false
  accessKey: 'fiubrother'
  secretKey: 'alwayswatching'
logger:
  host: 'localhost'
  port: 12201
server:
  port: 8080
  stageTime: 5
db:
  user: 'fiubrother'
  host: 'localhost'
  database: 'big_fiubrother'
  password: 'alwayswatching'
  port: 5432
metadata:
  video:
    width: 1280
    height: 720